# Generated by Django 5.0.3 on 2024-03-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Touch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('donor_email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=30)),
            ],
        ),
    ]
