# Generated by Django 5.0.3 on 2024-03-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touch',
            old_name='donor_email',
            new_name='email',
        ),
    ]
